### ISSUE TITLE
[Paper] Color scale

### ISSUE THREAD

**Issue by jm-begon** [ashafaei/OD-test#1]
The work done is impressive. My only major issue is about the use of the continuous color scale for the various bar plots. Although pretty, it makes for a hard reading of the plots when trying to find the bar from the legend. I believe a qualitative color palette would be more readable and more colorblind friendly. 

Also, I did not quite get how the threshold of some methods (typically ODIN) were obtained. Is it optimized by grid search like the perturbation step size and the temperature ?

Hope it will get published soon.

**Comment by ashafaei** [comment]
@jm-begon 
Thank you! Sorry I didn't notice this issue earlier. The notification must've been buried in my mailbox. As for the figures, we have updated them to address the confusion. The new version would show up on arXiv shortly.
![https://www.cs.ubc.ca/~shafaei/dataset/od2.png](https://www.cs.ubc.ca/~shafaei/dataset/od2.png)

Finding the optimal threshold under our context is a convex optimization problem which I think has even a closed-form solution. We did not think hard on this part and used straightforward gradient descent to find the threshold.

For the other parameters, like the step size and temperature, we use a grid search. We first set the parameters of the grid search [here](https://github.com/ashafaei/OD-test/blob/master/methods/odin.py#L208-L209), then optimize the threshold with GD [here](https://github.com/ashafaei/OD-test/blob/master/methods/odin.py#L214-L253).

Let me know if have any further questions.

Cheers,
Alireza
