### ISSUE TITLE
Are there any plan to release a Python 3 version of this project?

### ISSUE THREAD

**Issue by yw981** [ashafaei/OD-test#3]
Are there any plan to release a Python 3 version of this project since Python 2 is retiring ？
Thanks

**Comment by ashafaei** [comment]
Hi @yw981 
I'm not sure if I'd find the time to update the repository myself. Anyone is welcome to make a pull request for an update. But I think the more urgent update would be compatibility with the latest PyTorch. A retirement of python 2 would simply mean no more improvements and bug fixes. The expected lifecycle of this repository is way shorter than it takes for python 2 to disappear.
